# Generated by Django 5.1.15 on 2026-05-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0004_scrapealert"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="operation_type",
            field=models.CharField(
                choices=[("sale", "Продаж"), ("rent", "Оренда"), ("unknown", "—")],
                db_index=True,
                default="unknown",
                max_length=16,
            ),
        ),
    ]
